# Generated by Django 6.0.5 on 2026-05-21 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_location_name",
                    models.CharField(default="Current Location", max_length=255),
                ),
                ("start_location_lat", models.FloatField()),
                ("start_location_lon", models.FloatField()),
                (
                    "pickup_location_name",
                    models.CharField(default="Pickup Location", max_length=255),
                ),
                ("pickup_location_lat", models.FloatField()),
                ("pickup_location_lon", models.FloatField()),
                (
                    "dropoff_location_name",
                    models.CharField(default="Dropoff Location", max_length=255),
                ),
                ("dropoff_location_lat", models.FloatField()),
                ("dropoff_location_lon", models.FloatField()),
                (
                    "distance_miles",
                    models.FloatField(help_text="Total trip distance in miles"),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        help_text="Total transit duration in seconds (driving + HOS breaks)"
                    ),
                ),
                (
                    "polyline",
                    models.TextField(
                        help_text="JSON representation of route coordinates [[lat, lon], ...]"
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "initial_cycle_hours",
                    models.FloatField(
                        default=0.0, help_text="Starting cycle hours used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("START", "Start/Current Location"),
                            ("PICKUP", "Pickup/Loading Location"),
                            ("FUEL", "Fuel Stop"),
                            ("REST", "30-minute Rest Break"),
                            ("OVERNIGHT", "10-hour Overnight Reset"),
                            ("DROPOFF", "Dropoff/Unloading Location"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                (
                    "duration_seconds",
                    models.FloatField(help_text="Time spent at this stop in seconds"),
                ),
                (
                    "distance_from_previous_miles",
                    models.FloatField(
                        default=0.0, help_text="Distance from previous stop in miles"
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        help_text="Order in which this stop occurs (0-indexed)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="HOS reasoning or stop details", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "unique_together": {("trip", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="The date of the log entry")),
                (
                    "driving_seconds",
                    models.FloatField(
                        default=0.0, help_text="Time spent driving in seconds"
                    ),
                ),
                (
                    "on_duty_seconds",
                    models.FloatField(
                        default=0.0,
                        help_text="Time spent on duty (non-driving) in seconds",
                    ),
                ),
                (
                    "off_duty_seconds",
                    models.FloatField(
                        default=0.0, help_text="Time spent off duty/resting in seconds"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Start of the log day (first activity)"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="End of the log day (last activity)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("trip", "date")},
            },
        ),
    ]
